#!/bin/sh
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 "username/password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.ryerson.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF

create table CUSTOMER(
  ID INT NOT NULL,
  NAME VARCHAR2(20) NOT NULL,
  PHONE_NUMBER INT NOT NULL,
  CREDIT_CARD INT NOT NULL,
  VALET INT DEFAULT 0 NOT NULL,
  PRIMARY KEY (ID));

create table ROOM( 
  ROOM_ID INT NOT NULL,
  ROOM_TYPE VARCHAR2(20) NOT NULL,
  CAPACITY INT NOT NULL,
  AVAILABILITY VARCHAR(20) DEFAULT 'Vacant',
  PRICE INT NOT NULL,
  PRIMARY KEY (ROOM_ID));
  
create table EMPLOYEE(
  E_ID INT NOT NULL,
  NAME VARCHAR(20) NOT NULL,
  PARTTIME_FULLTIME VARCHAR(20) NOT NULL,
  D_O_H date NOT NULL,
  PRIMARY KEY (E_ID));
  
create table PARKINGSPOT( 
  SPOT_NUMBER INT NOT NULL,
  AVALIABILITY VARCHAR(20) DEFAULT'Available' NOT NULL,
  PRIMARY KEY (SPOT_NUMBER));
  
create table AMENITIES( 
  ID INT NOT NULL,
  GYM VARCHAR(20) NOT NULL,
  POOL VARCHAR(20) NOT NULL,
  ROOM_SERVICE VARCHAR(20) NOT NULL,
  BREAKFAST VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID));
  
create table ONLINEBOOKING(
  B_ID INT NOT NULL,
  ID INT NOT NULL,
  A_ID INT NOT NULL,
  NUMBER_OF_GUESTS INT NOT NULL,
  CHECK_IN date NOT NULL,
  CHECK_OUT date NOT NULL,
  ROOM_ID INT NOT NULL,
  FOREIGN KEY (ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ROOM_ID),
  FOREIGN KEY (A_ID) REFERENCES AMENITIES(ID),
  PRIMARY KEY (B_ID));
  
create table VALET(
  L_PLATE VARCHAR(20) NOT NULL,
  ID INT NOT NULL,
  E_ID INT NOT NULL,
  SPOT_NUMB INT NOT NULL,
  FOREIGN KEY (SPOT_NUMB) REFERENCES PARKINGSPOT(SPOT_NUMBER),
  FOREIGN KEY (ID) REFERENCES CUSTOMER(ID),
  FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(E_ID),
  PRIMARY KEY (L_PLATE));
  
create table BOOKED(
  ID INT REFERENCES CUSTOMER(ID) NOT NULL,
  B_ID INT NOT NULL REFERENCES ONLINEBOOKING(B_ID),
  PRIMARY KEY(ID, B_ID));

create table RESERVED(
  ROOM_NUMB INT NOT NULL REFERENCES ROOM(ROOM_ID),
  B_ID INT NOT NULL REFERENCES ONLINEBOOKING(B_ID),
  PRIMARY KEY(ROOM_NUMB, B_ID));

create table EXTRAS(
  A_ID INT NOT NULL REFERENCES AMENITIES(ID),
  B_ID INT NOT NULL REFERENCES ONLINEBOOKING(B_ID) ,
  PRIMARY KEY(A_ID, B_ID));

create table PARKED(
  E_ID INT NOT NULL REFERENCES EMPLOYEE(E_ID),
  ID INT NOT NULL REFERENCES CUSTOMER(ID),
  PRIMARY KEY(E_ID, ID));
  
create table INUSE(
  L_PLATE VARCHAR(20) NOT NULL REFERENCES VALET(L_PLATE),
  SPOT_NUMBER INT NOT NULL REFERENCES PARKINGSPOT(SPOT_NUMBER),
  PRIMARY KEY(L_PLATE, SPOT_NUMBER));
exit;
EOF